import argparse
import hashlib
import json
import re
import urllib.request
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
INPUT = PROJECT_ROOT / "companion" / "requirements.in"
OUTPUT = PROJECT_ROOT / "companion" / "requirements.lock"
REQUIREMENT_PATTERN = re.compile(r"^(?P<name>[a-z0-9-]+)==(?P<version>[^;]+)(?P<marker>.*)$")


@dataclass(frozen=True)
class LockedRequirement:
    name: str
    version: str
    marker: str
    hashes: tuple[str, ...]


def main() -> None:
    arguments = parse_arguments()
    requirements = load_requirements(arguments.metadata_directory)
    OUTPUT.write_text(render_lock(requirements), encoding="utf-8", newline="\n")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the universal hashed Python lock")
    parser.add_argument("--metadata-directory", type=Path)
    return parser.parse_args()


def load_requirements(metadata_directory: Path | None) -> list[LockedRequirement]:
    requirements = []
    for line in INPUT.read_text(encoding="utf-8").splitlines():
        if line and not line.startswith("#"):
            requirements.append(load_requirement(line, metadata_directory))
    return requirements


def load_requirement(line: str, metadata_directory: Path | None) -> LockedRequirement:
    match = REQUIREMENT_PATTERN.fullmatch(line)
    if match is None:
        raise RuntimeError(f"Requirement is not exactly pinned: {line}")
    name, version, marker = match.group("name", "version", "marker")
    metadata = load_metadata(name, version, metadata_directory)
    hashes = release_hashes(metadata)
    return LockedRequirement(name, version, marker, hashes)


def load_metadata(name: str, version: str, directory: Path | None) -> dict:
    if directory is not None:
        return json.loads((directory / f"{name}.json").read_text(encoding="utf-8"))
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=30) as response:
        return json.load(response)


def release_hashes(metadata: dict) -> tuple[str, ...]:
    hashes = {
        artifact["digests"]["sha256"]
        for artifact in metadata["urls"]
        if not artifact.get("yanked", False)
    }
    if not hashes:
        raise RuntimeError("Package release has no non-yanked artifacts")
    return tuple(sorted(hashes))


def render_lock(requirements: list[LockedRequirement]) -> str:
    digest = hashlib.sha256(INPUT.read_bytes()).hexdigest()
    lines = [
        "# Generated by: python3 scripts/generate_python_lock.py",
        f"# requirements.in sha256: {digest}",
        "# Every direct and transitive Phase 1 dependency is exactly pinned.",
        "",
    ]
    for requirement in requirements:
        lines.extend(render_requirement(requirement))
    return "\n".join(lines) + "\n"


def render_requirement(requirement: LockedRequirement) -> list[str]:
    pinned = f"{requirement.name}=={requirement.version}{requirement.marker}"
    hashes = [f"    --hash=sha256:{value}" for value in requirement.hashes]
    if not hashes:
        return [pinned]
    lines = [f"{pinned} \\"]
    for index, value in enumerate(hashes):
        suffix = " \\" if index < len(hashes) - 1 else ""
        lines.append(value + suffix)
    return lines


if __name__ == "__main__":
    main()
